# Generated by Django 3.2.6 on 2021-11-18 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('area_in_sq_meters', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('area_in_sq_meters', models.FloatField()),
                ('number_of_hospitals', models.IntegerField()),
                ('number_of_national_parks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.continent')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('area_in_sq_meters', models.FloatField()),
                ('number_of_roads', models.IntegerField(null=True)),
                ('number_of_trees', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.country')),
            ],
        ),
    ]
