# Generated by Django 3.2.6 on 2021-11-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_auto_20211118_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='continent_id',
            new_name='continent',
        ),
    ]
